# Generated by Django 4.1 on 2022-08-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('retailer', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
