# Generated by Django 4.1 on 2022-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
