# Generated by Django 4.1 on 2022-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_retailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='abc', max_length=80),
        ),
    ]
