# Generated by Django 4.1 on 2022-08-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
