# Generated by Django 4.1 on 2022-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnails_urls',
            field=models.URLField(default='', max_length=400),
        ),
    ]
