# Generated by Django 4.1 on 2022-08-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_category_alter_product_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='retailer',
            new_name='product_id',
        ),
    ]
